// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBivc4NDlPQYQKMiAbMMU5NnSA97schasQ',
    appId: '1:69550257474:web:2e59313ba287968f1884db',
    messagingSenderId: '69550257474',
    projectId: 'watermelon-summer-project',
    authDomain: 'watermelon-summer-project.firebaseapp.com',
    storageBucket: 'watermelon-summer-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ32Yw7Zah1U1GgSLWVSyX5zorbKt_qyg',
    appId: '1:69550257474:android:33013cc35bd701f71884db',
    messagingSenderId: '69550257474',
    projectId: 'watermelon-summer-project',
    storageBucket: 'watermelon-summer-project.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWxv1KbIHl8M5epAp8uWYx-hvz69w43_E',
    appId: '1:69550257474:ios:9f71026470dbe4dc1884db',
    messagingSenderId: '69550257474',
    projectId: 'watermelon-summer-project',
    storageBucket: 'watermelon-summer-project.firebasestorage.app',
    iosBundleId: 'com.example.flutterPlayground',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWxv1KbIHl8M5epAp8uWYx-hvz69w43_E',
    appId: '1:69550257474:ios:9f71026470dbe4dc1884db',
    messagingSenderId: '69550257474',
    projectId: 'watermelon-summer-project',
    storageBucket: 'watermelon-summer-project.firebasestorage.app',
    iosBundleId: 'com.example.flutterPlayground',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBivc4NDlPQYQKMiAbMMU5NnSA97schasQ',
    appId: '1:69550257474:web:b43c7ba04f53e3c21884db',
    messagingSenderId: '69550257474',
    projectId: 'watermelon-summer-project',
    authDomain: 'watermelon-summer-project.firebaseapp.com',
    storageBucket: 'watermelon-summer-project.firebasestorage.app',
  );
}
